spring:
  application:
    name: bank-bot
  jpa:
    hibernate:
      ddl-auto: update  # or `none` if schema managed externally
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN