spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  main:
    web-application-type: none
  application:
    name: bank-bot
  jpa:
    hibernate:
      ddl-auto: none  # or `none` if schema managed externally
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN